### ISSUE TITLE
After updating dokuwiki to 2024-02-06 "Kaos", the extension crashes

### ISSUE THREAD

**Issue by francoisthill** [dwp-forge/tablewidth#8]
**Error shown on screen**
TypeError: call_user_func_array(): Argument #1 ($callback) must be a valid callback, class Doku_Renderer_metadata does not have a method "table_align"

An unforeseen error has occured. This is most likely a bug somewhere.

More info has been written to the DokuWiki error log.

**Error log**
2024-02-06 21:09:47     /var/www/html/dokuwiki/inc/parserutils.php(535) TypeError: call_user_func_array(): Argument #1 ($callback) must be a valid callback, class Doku_Renderer_metadata does not have a method "table_align"
  #0 /var/www/html/dokuwiki/inc/parserutils.php(299): p_render_metadata()
  #1 /var/www/html/dokuwiki/inc/common.php(262): p_get_metadata()
  #2 /var/www/html/dokuwiki/doku.php(101): pageinfo()
  #3 {main}

Thank you

I very much enjoy your extension.

François

**Comment by francoisthill** [comment]
This problem seems not to be in the extension: https://github.com/dokuwiki/dokuwiki/issues/4186.
